--- 
- name: docker
  hosts: localhost
  become: false
  gather_facts: true
  roles:
    - docker
   
- name: add Users
  hosts: dockers
  gather_facts: false
  become: true
  roles: 
    - users

- name: "install httpd on container 1"
  hosts: container1
  become: false
  roles:
    - httpdRole
  

- name: "install nginx on container 2"
  hosts: container2
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - nginxConfig
 
  
  
