--- 
- name: docker
  hosts: localhost
  become: false
  gather_facts: true
  roles:
    - docker
   
- name: add Users
  hosts: dockers
  gather_facts: false
  become: true
  roles: 
    - users

- name: configure with httpd 
  hosts: all
  gather_facts: false
  become: true
  roles: 
    - httpdRole
  
