--- 
- name: Container start
  docker_container:
    name: "{{ item.name }}"
    image: "{{ image_name }}"
    state: started
    ports:
      - "{{ item.port }}:80"
    security_opts:
          - "label:disable"
    privileged: true
    command: /sbin/init
  loop: "{{ list_containers }}"
  register: containers
  

- name: Create a in-memory inventory
  add_host:
    host: "{{ item.invocation.module_args.name }}"
    group: dockers
    ansible_user: root
    ansible_connection: docker
  loop: "{{ containers.results }}"

- name: Create a default inventory
  copy:
    content: |
      [web]
      {% for i in containers.results %}
      {{ i.invocation.module_args.name }} ansible_host={{ i.container.NetworkSettings.IPAddress }}
      {% endfor %}
      [all:vars]
      ansible_user=chaimae
      ansible_ssh_private_key_file={{ keypair_path }}
    dest: "{{ inventory_path }}"

- name: Create ansible.cfg
  copy:
    content: |
      [defaults]
      inventory          = /root/Ansible/inventory.ini
      host_key_checking  = False
      force_color        = True
      forks              = 1
     
      [ssh_connection]
      ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    dest: "{{ ansible_cfg_path }}"

- name: create ssh keypair
  community.crypto.openssh_keypair:
    path: " {{ keypair_path }}.pub" 
  register: keypair

- debug: var=keypair



