--- 
- name: Container start
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ image_name }}"
    state: started
    ports:
      - "{{ item.port }}:83"
    security_opts:
          - "label:disable"
    privileged: true
  loop: "{{ containers }}"
  register: containers 