--- 
- name: Container start
  docker_container:
    name: "{{ item.name }}"
    image: "{{ image_name }}"
    state: started
    ports:
      - "{{ item.port }}:80"
    security_opts:
          - "label:disable"
    privileged: true
    command: /sbin/init
  loop: "{{ containers }}"
  register: containers 



