---
# tasks file for nginxConfig

- name: "Installing haproxy"
  package:
    name: "haproxy"
    state: present

- name: "starting haproxy services"
  service:
    name: "haproxy"
    state: started
