---
# tasks file for users

- name: add chaimae user to each node
  user:
    name: chaimae
    state: present

- name: start sshd
  service:
    name: sshd
    state: started
  tags:
    - travis

- name: create ssh directory to chaimae
  file:
    path: ./.ssh 
    state: directory
    mode: '0755'
    owner: chaimae
    group: chaimae

- name: copy pub key to nodes
  copy:
    src: "{{ keypair_path }}.pub"
    dest: ./.ssh/authorized_keys
    mode: '0600'
    owner: chaimae
    group: chaimae
  tags:
    - travis

- name: update repo url
  shell: "sed -i 's|#baseurl=http://mirror.chaimae.org|baseurl=http://vault.chaimae.org|g' /etc/yum.repos.d/chaimae-Linux-*;"